import AnalyticsFrame from "@/components/producer/analytics/AnalyticsFrame";
import { DefName, Delta, EvidenceOf, MetricValue, RateBasis, type Unit } from "@/components/producer/analytics/bits";
import FunnelList from "@/components/producer/analytics/FunnelList";
import SeriesChart from "@/components/producer/analytics/SeriesChart";
import { loadAnalyticsPage } from "@/components/producer/analytics/load";
import { t } from "@/lib/i18n";
import type { RateMetric } from "@/lib/analytics/types";

// /producer/titles/[id]/analytics — Overview: the range control, five
// defined headline measures with a valid previous-period comparison, one
// time-series chart with a table alternative, viewing and monetization
// summaries, the monetization funnel, the freshness line, and two to four
// descriptive takeaways generated by rules from the displayed numbers, each
// linking to the view that explains it. Nothing here claims a cause.

export const dynamic = "force-dynamic";

const VIEW_HREF = { overview: "", revenue: "/revenue", episodes: "/episodes", acquisition: "/acquisition" } as const;

export default async function AnalyticsOverview({ params, searchParams }: { params: { id: string }; searchParams: { range?: string } }) {
  const data = await loadAnalyticsPage(params.id, "overview", searchParams);
  const { locale, record: a, base, query } = data;
  const o = a.overview;
  return (
    <AnalyticsFrame data={data} view="overview">
      {o && (
        <>
          <section className="an-headlines" aria-label={t(locale, "an.ov.headlines")}>
            {o.headlines.map((h) => (
              <div key={h.key} className="an-headline">
                <span className="an-headline-label"><DefName metricKey={h.key} locale={locale} /></span>
                <strong className="an-headline-value"><MetricValue m={h.metric} unit={h.unit as Unit} locale={locale} compact /></strong>
                {"denominator" in h.metric && <RateBasis m={h.metric as RateMetric} locale={locale} />}
                <Delta c={h.comparison} locale={locale} />
                {h.href && <a className="an-headline-link" href={`${h.href}${query}`}>{t(locale, "an.ov.detail")} ›</a>}
              </div>
            ))}
          </section>
          <p className="an-compare-note rs-meta">
            {o.previous_period ? <span>{t(locale, "an.ov.prevPeriod", { from: o.previous_period.from, to: o.previous_period.to })}</span> : <span>{t(locale, "an.ov.noPrevPeriod")}</span>}
            <span>{t(locale, "an.ov.deltaLegend")}</span>
          </p>

          <section className="rs-panel an-panel">
            <div className="rs-panel-head"><div><h2>{t(locale, "an.ov.trend")}</h2><p>{t(locale, "an.ov.trendSub")}</p></div></div>
            <div className="rs-panel-body"><SeriesChart series={o.series} locale={locale} /></div>
          </section>

          <div className="rs-grid an-grid">
            <section className="rs-panel">
              <div className="rs-panel-head"><div><h2>{t(locale, "an.ov.viewing")}</h2><p>{t(locale, "an.ov.viewingSub")}</p></div><a className="rs-panel-aside" href={`${base}/episodes${query}`}>{t(locale, "an.nav.episodes")} ›</a></div>
              <dl className="an-kv">
                {o.viewing.map((v) => (
                  <div key={v.key}><dt><DefName metricKey={v.key} locale={locale} /> <EvidenceOf m={v.metric} locale={locale} /></dt><dd><MetricValue m={v.metric} unit={v.key === "watch_seconds_avg" ? "seconds" : (v.unit as Unit)} locale={locale} />{"denominator" in v.metric && <RateBasis m={v.metric} locale={locale} />}</dd></div>
                ))}
              </dl>
            </section>
            <section className="rs-panel">
              <div className="rs-panel-head"><div><h2>{t(locale, "an.ov.monetization")}</h2><p>{t(locale, "an.ov.monetizationSub")}</p></div><a className="rs-panel-aside" href={`${base}/revenue${query}`}>{t(locale, "an.nav.revenue")} ›</a></div>
              <dl className="an-kv">
                {o.monetization.map((v) => (
                  <div key={v.key}><dt><DefName metricKey={v.key} locale={locale} /> <EvidenceOf m={v.metric} locale={locale} /></dt><dd><MetricValue m={v.metric} unit={v.unit as Unit} locale={locale} />{"denominator" in v.metric && <RateBasis m={v.metric} locale={locale} />}</dd></div>
                ))}
              </dl>
            </section>
          </div>

          <div className="rs-grid an-grid">
            <section className="rs-panel">
              <div className="rs-panel-head"><div><h2>{t(locale, "an.ov.takeaways")}</h2><p>{t(locale, "an.ov.takeawaysSub")}</p></div></div>
              <ol className="an-takeaways">
                {o.takeaways.map((k) => (
                  <li key={k.key + JSON.stringify(k.vars ?? {})}>
                    <span>{t(locale, k.key, k.vars)}</span>
                    <a href={`${base}${VIEW_HREF[k.view]}${query}`}>{t(locale, `an.nav.${k.view}`)} ›</a>
                  </li>
                ))}
              </ol>
            </section>
            {a.funnel && (
              <section className="rs-panel">
                <div className="rs-panel-head"><div><h2>{t(locale, "an.funnel.title")}</h2><p>{t(locale, "an.funnel.sub")}</p></div></div>
                <div className="rs-panel-body"><FunnelList f={a.funnel} locale={locale} /></div>
              </section>
            )}
          </div>
        </>
      )}
    </AnalyticsFrame>
  );
}
