// The paid-social creative brief: what a human editor cuts from. One table
// of the ad scenes in rank order (timestamps quoted from the real cues, cut
// length, angle, hook, opening text, why), then the platform picks — the
// selected title and hook — and the remaining hook copy so the editor can
// test alternates without opening the app. Dismissed clips and dismissed
// variants stay out; a shortlisted clip is marked because the shortlist is
// the editor's first pass. English by default: the audience is a U.S.
// editor; `locale: "zh"` flips the chrome and prefers the zh rationale.

import { AD_ANGLE_LABELS, type Clip, type Episode, type Title, type Variant } from "@/lib/types";
import { clockRange, clockTime } from "./time";
import { type DocLocale, docShell, esc, escMultiline, metaList, pill } from "./html";

const LABELS = {
  en: {
    doc: "Paid-social creative brief",
    logline: "Logline",
    genre: "Genre",
    scenes: "Top ad scenes",
    scenesIntro: "In rank order within each episode. Timestamps are on the source episode; cut length is the recommended finished length.",
    none: "No clip suggestions yet. Run the clip finder on the title's pack page.",
    rank: "#",
    episode: "Ep",
    time: "Timestamps",
    cut: "Cut",
    angle: "Angle",
    hook: "Hook",
    opening: "Opening text",
    why: "Why it could work",
    shortlisted: "Shortlisted",
    picks: "Platform picks",
    pickTitle: "Selected title",
    pickHook: "Selected hook",
    noPick: "Not chosen yet",
    hooks: "Hook copy",
    hooksIntro: "Every candidate hook; the selected one is marked.",
    angles: "Ad angles",
    seconds: "s",
    foot: "Generated by Pulsar Studio. External ids only.",
  },
  zh: {
    doc: "付费社交投放创意简报",
    logline: "一句话梗概",
    genre: "类型",
    scenes: "推荐广告片段",
    scenesIntro: "按每集内的排序列出。时间码对应原片；剪辑时长为建议成片长度。",
    none: "尚无片段建议。请在该剧的创意包页面运行片段查找。",
    rank: "#",
    episode: "集",
    time: "时间码",
    cut: "时长",
    angle: "角度",
    hook: "钩子",
    opening: "开场文字",
    why: "为什么可行",
    shortlisted: "已入围",
    picks: "平台选定",
    pickTitle: "选定标题",
    pickHook: "选定钩子",
    noPick: "尚未选定",
    hooks: "钩子文案",
    hooksIntro: "全部候选钩子；已选定的一条已标出。",
    angles: "投放角度",
    seconds: "秒",
    foot: "由 Pulsar Studio 生成。仅含外部编号。",
  },
} as const;

export type BriefInput = {
  title: Pick<Title, "name_zh" | "name_en" | "external_id" | "genre" | "logline_en" | "logline_zh">;
  clips: Clip[];
  variants: Variant[];
  /** Maps clips.episode_id to a number; without it the table shows the clip's rank only. */
  episodes?: Array<Pick<Episode, "id" | "number" | "name_en" | "name_zh">>;
  locale?: DocLocale;
};

function angleLabel(a: Clip["angle"] | null, locale: DocLocale): string {
  if (!a) return "";
  const l = AD_ANGLE_LABELS[a];
  return l ? (locale === "zh" ? l.zh : l.en) : a;
}

function variantCard(v: Variant | undefined, label: string, locale: DocLocale, none: string): string {
  const L = LABELS[locale];
  if (!v) return `<div class="card"><div class="label">${esc(label)}</div><p class="faint">${esc(none)}</p></div>`;
  const why = locale === "zh" ? v.rationale_zh ?? v.rationale_en : v.rationale_en ?? v.rationale_zh;
  const second = v.text_zh;
  return `<div class="card pick">
  <div class="label">${esc(label)}</div>
  <p style="font-size:16px;margin-top:4px">${esc(v.text_en)}</p>
  ${second ? `<p class="small muted">${esc(second)}</p>` : ""}
  ${why ? `<p class="small" style="margin-top:6px"><span class="faint">${esc(L.why)}</span> ${esc(why)}</p>` : ""}
  <div class="tags" style="margin-top:6px">${v.tags.map((t) => pill(angleLabel(t, locale), "neutral")).join("")}<span class="mono micro faint" style="margin-left:6px">${esc(v.external_id)}</span></div>
</div>`;
}

export function briefHtml(i: BriefInput): string {
  const locale: DocLocale = i.locale ?? "en";
  const L = LABELS[locale];
  const epNum = new Map((i.episodes ?? []).map((e) => [e.id, e.number]));
  const heading = locale === "zh" ? i.title.name_zh : i.title.name_en ?? i.title.name_zh;
  const sub = locale === "zh" ? i.title.name_en : i.title.name_zh;
  const logline = locale === "zh" ? i.title.logline_zh ?? i.title.logline_en : i.title.logline_en ?? i.title.logline_zh;

  const clips = i.clips
    .filter((c) => c.status !== "dismissed")
    .slice()
    .sort((a, b) => (epNum.get(a.episode_id) ?? 0) - (epNum.get(b.episode_id) ?? 0) || a.rank - b.rank);

  const rows = clips
    .map((c) => {
      const ep = epNum.get(c.episode_id);
      const why = locale === "zh" ? c.why_zh || c.why_en : c.why_en || c.why_zh;
      return `<tr>
  <td class="num">${c.rank}${c.status === "shortlisted" ? `<br>${pill(L.shortlisted, "accent")}` : ""}</td>
  <td class="num">${ep !== undefined ? ep : ""}</td>
  <td class="num">${esc(clockRange(c.start_ms, c.end_ms))}<br><span class="micro faint">${esc(clockTime(c.end_ms - c.start_ms))}</span></td>
  <td class="num">${c.cut_length_s !== null ? `${c.cut_length_s}${esc(L.seconds)}` : ""}</td>
  <td>${c.angle ? pill(angleLabel(c.angle, locale), "neutral") : ""}</td>
  <td><strong style="font-weight:500">${esc(c.hook_en)}</strong>${c.opening_text_en ? `<br><span class="small muted">${esc(L.opening)}: ${esc(c.opening_text_en)}</span>` : ""}<br><span class="mono micro faint">${esc(c.external_id)}</span></td>
  <td class="small">${escMultiline(why)}</td>
</tr>`;
    })
    .join("\n");

  const table = clips.length
    ? `<table>
<thead><tr><th class="num">${esc(L.rank)}</th><th class="num">${esc(L.episode)}</th><th class="num">${esc(L.time)}</th><th class="num">${esc(L.cut)}</th><th>${esc(L.angle)}</th><th>${esc(L.hook)}</th><th>${esc(L.why)}</th></tr></thead>
<tbody>${rows}</tbody>
</table>`
    : `<p class="small faint" style="margin-top:8px">${esc(L.none)}</p>`;

  const live = i.variants.filter((v) => v.status !== "dismissed");
  const selTitle = live.find((v) => v.kind === "title" && v.selected);
  const selHook = live.find((v) => v.kind === "hook" && v.selected);
  const hooks = live.filter((v) => v.kind === "hook");
  const angles = live.filter((v) => v.kind === "ad_angle");

  const hookList = hooks.length
    ? `<ol class="plain">${hooks
        .map(
          (h) =>
            `<li>${esc(h.text_en)}${h.selected ? ` ${pill(L.pickHook, "accent")}` : ""}${h.text_zh ? `<br><span class="small muted">${esc(h.text_zh)}</span>` : ""}</li>`,
        )
        .join("")}</ol>`
    : "";

  const angleList = angles.length
    ? angles
        .map(
          (a) =>
            `<div class="card"><p>${esc(a.text_en)}</p>${a.text_zh ? `<p class="small muted">${esc(a.text_zh)}</p>` : ""}<div class="tags" style="margin-top:6px">${a.tags.map((t) => pill(angleLabel(t, locale), "neutral")).join("")}</div></div>`,
        )
        .join("")
    : "";

  const body = `<header class="head">
  <div>
    <div class="label">${esc(L.doc)}</div>
    <h1>${esc(heading)}</h1>
    ${sub ? `<div class="sub muted">${esc(sub)}</div>` : ""}
  </div>
  <div class="mono micro faint">${esc(i.title.external_id)}</div>
</header>
${metaList([
  [L.genre, i.title.genre],
  [L.logline, logline],
])}

<h2>${esc(L.scenes)}</h2>
<p class="small muted">${esc(L.scenesIntro)}</p>
${table}

<h2>${esc(L.picks)}</h2>
<div class="grid2">
${variantCard(selTitle, L.pickTitle, locale, L.noPick)}
${variantCard(selHook, L.pickHook, locale, L.noPick)}
</div>

${hookList ? `<h2>${esc(L.hooks)}</h2><p class="small muted">${esc(L.hooksIntro)}</p>${hookList}` : ""}
${angleList ? `<h2>${esc(L.angles)}</h2>${angleList}` : ""}

<footer class="foot">${esc(L.foot)}</footer>`;

  return docShell({ lang: locale, title: `${heading} · ${L.doc}`, body });
}
