// The bilingual diff document: the file the producer (制片方) reads, signs off
// on and keeps. It renders from the frozen snapshot only, so the same
// version always prints the same pages, and the header names the version
// (ver_ id + sha256 + approval state) so a printout can be matched to the
// row it came from. Major changes lead, because that is what the partner
// reviews first; then every scene, one per printed page, each line as a
// three-part block: the Chinese source, the Chinese back-translation the
// partner actually judges (set larger, tinted), and the English underneath,
// small, with 为什么这样改编 and the tone shift.
//
// Chrome strings live in LABELS below in both languages: this is a
// generated file, not the app, so it does not go through the dictionaries.

import {
  TAG_LABELS,
  type ApprovalMode,
  type ChangeType,
  type Episode,
  type SnapshotAdaptedLine,
  type SnapshotLine,
  type SnapshotScene,
  type Title,
  type VersionSnapshot,
  type VersionStatus,
} from "@/lib/types";
import { clockRange, clockTime } from "./time";
import { type DocLocale, docShell, esc, escMultiline, fmtDate, metaList, pill } from "./html";

const LABELS = {
  en: {
    doc: "Adaptation review",
    episode: "Episode",
    version: "Version",
    versionId: "Version id",
    sha: "Snapshot sha256",
    state: "State",
    submitted: "Submitted",
    approved: "Approved",
    approvedOnBehalf: "Approved on behalf (evidence on file)",
    producer: "Producer",
    target: "Target",
    scenes: "Scenes",
    lines: "Lines",
    changed: "Lines changed",
    major: "Major changes",
    majorNone: "No line is marked as a major change in this version.",
    majorIntro: "Lines that change a name, a title or who is at fault. Read these first.",
    scene: "Scene",
    context: "Context",
    source: "Original",
    back: "Back-translation",
    english: "English",
    why: "Why this version",
    tone: "Tone",
    cut: "Cut — this line is not in the U.S. script.",
    unadapted: "Not adapted yet",
    majorFlag: "Major",
    foot: "Generated by Pulsar Studio. External ids only; nothing in this file links to a database row.",
    status: {
      draft: "Draft",
      in_review: "In review",
      approved: "Approved",
      superseded: "Superseded",
    } as Record<VersionStatus, string>,
    change: {
      keep: "Kept",
      literal: "Literal",
      rewrite: "Rewritten",
      tighten: "Tightened",
      tone: "Tone",
      cultural: "Cultural swap",
      pacing: "Pacing",
      cut: "Cut",
      add: "Added",
    } as Record<ChangeType, string>,
  },
  zh: {
    doc: "改编审阅稿",
    episode: "第 {n} 集",
    version: "版本",
    versionId: "版本编号",
    sha: "快照 sha256",
    state: "状态",
    submitted: "提交时间",
    approved: "批准时间",
    approvedOnBehalf: "代为批准（已留存依据）",
    producer: "制片方",
    target: "目标市场",
    scenes: "场次",
    lines: "台词",
    changed: "改动台词",
    major: "重大改动",
    majorNone: "本版本没有标记为重大改动的台词。",
    majorIntro: "涉及人名、称呼或责任归属的改动，请先审阅。",
    scene: "第 {n} 场",
    context: "场景背景",
    source: "原文",
    back: "回译",
    english: "英文",
    why: "为什么这样改编",
    tone: "语气",
    cut: "删除 — 这句台词不在美版剧本中。",
    unadapted: "尚未改编",
    majorFlag: "重大",
    foot: "由 Pulsar Studio 生成。仅含外部编号，不关联任何数据库记录。",
    status: {
      draft: "草稿",
      in_review: "审阅中",
      approved: "已批准",
      superseded: "已替换",
    } as Record<VersionStatus, string>,
    change: {
      keep: "保留",
      literal: "直译",
      rewrite: "改写",
      tighten: "精简",
      tone: "语气调整",
      cultural: "文化替换",
      pacing: "节奏调整",
      cut: "删除",
      add: "新增",
    } as Record<ChangeType, string>,
  },
} as const;

export type DiffDocumentInput = {
  title: Pick<Title, "name_zh" | "name_en" | "external_id" | "genre">;
  episode: Pick<Episode, "number" | "name_zh" | "name_en" | "external_id">;
  snapshot: VersionSnapshot;
  locale: DocLocale;
  /**
   * The version row the snapshot came from; without it the header says
   * "draft" and prints no hash (a draft export before submit).
   */
  version?: {
    status: VersionStatus;
    snapshot_sha256: string | null;
    submitted_at?: string | null;
    approved_at?: string | null;
    approval_mode?: ApprovalMode | null;
  } | null;
  /** Shown in the header when known (the snapshot carries only the producer uuid). */
  producer_name?: string | null;
};

const fill = (s: string, n: number) => s.replace("{n}", String(n));

function statusTone(s: VersionStatus): "neutral" | "accent" | "success" | "warning" {
  return s === "approved" ? "success" : s === "in_review" ? "accent" : s === "draft" ? "warning" : "neutral";
}

type Joined = { adapted: SnapshotAdaptedLine; anchor: SnapshotLine | null; merged: SnapshotLine[] };

/** Adapted lines joined to their source lines; unadapted source lines come back separately, in seq order. */
function joinScene(scene: SnapshotScene): { joined: Joined[]; orphans: SnapshotLine[] } {
  const src = new Map(scene.lines.map((l) => [l.id, l]));
  const covered = new Set<string>();
  const joined = scene.adapted_lines.map((a) => {
    const anchor = a.line_id ? src.get(a.line_id) ?? null : null;
    if (anchor) covered.add(anchor.id);
    const merged = a.merges.flatMap((id) => {
      const m = src.get(id);
      if (m) covered.add(m.id);
      return m ? [m] : [];
    });
    return { adapted: a, anchor, merged };
  });
  const orphans = scene.lines.filter((l) => !covered.has(l.id));
  return { joined, orphans };
}

function tagPills(a: SnapshotAdaptedLine, locale: DocLocale): string {
  return a.tags
    .map((t) => TAG_LABELS[t])
    .filter(Boolean)
    .map((l) => pill(locale === "zh" ? l.zh : l.en, "neutral"))
    .join("");
}

function lineBlock(j: Joined, locale: DocLocale, sceneNumber?: number): string {
  const L = LABELS[locale];
  const a = j.adapted;
  const zh = [j.anchor?.text_zh ?? "", ...j.merged.map((m) => m.text_zh)].filter(Boolean).join(" ");
  const at = clockTime(a.start_ms ?? j.anchor?.start_ms);
  const who = j.anchor?.speaker;
  const why = locale === "zh" ? a.rationale_zh ?? a.rationale_en : a.rationale_en ?? a.rationale_zh;
  const tone = locale === "zh" ? a.tone_note_zh ?? a.tone_note_en : a.tone_note_en ?? a.tone_note_zh;
  const isCut = a.change_type === "cut" || a.text_en === null;
  const flags = [
    a.is_major ? pill(L.majorFlag, "error") : "",
    pill(L.change[a.change_type] ?? a.change_type, a.is_major ? "warning" : "neutral"),
    tagPills(a, locale),
  ].join("");
  const ref = sceneNumber !== undefined ? `<span class="faint micro"> · ${esc(fill(L.scene, sceneNumber))}</span>` : "";

  return `<div class="line${a.is_major ? " major" : ""}" id="${esc(a.external_id)}">
  <div class="at">${esc(at)}<br><span class="mono micro">${esc(a.external_id)}</span></div>
  <div>
    ${who ? `<div class="who">${esc(who)}${ref}</div>` : ref ? `<div class="who">${ref}</div>` : ""}
    <div class="zh"><span class="label">${esc(L.source)}</span><br>${esc(zh)}</div>
    ${
      isCut
        ? `<div class="cut">${esc(L.cut)}</div>`
        : `<div class="bt"><span class="label">${esc(L.back)}</span><br>${esc(a.back_translation_zh ?? "")}</div>
    <div class="en"><span class="label">${esc(L.english)}</span> ${esc(a.text_en)}</div>`
    }
    <div class="flags">${flags}</div>
    ${why ? `<div class="why"><b>${esc(L.why)}</b> ${esc(why)}</div>` : ""}
    ${tone ? `<div class="why"><b>${esc(L.tone)}</b> ${esc(tone)}</div>` : ""}
  </div>
</div>`;
}

function orphanBlock(l: SnapshotLine, locale: DocLocale): string {
  const L = LABELS[locale];
  return `<div class="line" id="${esc(l.external_id)}">
  <div class="at">${esc(clockTime(l.start_ms))}<br><span class="mono micro">${esc(l.external_id)}</span></div>
  <div>
    ${l.speaker ? `<div class="who">${esc(l.speaker)}</div>` : ""}
    <div class="zh"><span class="label">${esc(L.source)}</span><br>${esc(l.text_zh)}</div>
    <div class="flags">${pill(L.unadapted, "warning")}</div>
  </div>
</div>`;
}

function sceneSection(scene: SnapshotScene, locale: DocLocale): string {
  const L = LABELS[locale];
  const { joined, orphans } = joinScene(scene);
  // Interleave by seq so an unadapted source line sits where it belongs in the script.
  const entries: Array<{ seq: number; html: string }> = [
    ...joined.map((j) => ({ seq: j.adapted.seq, html: lineBlock(j, locale) })),
    ...orphans.map((l) => ({ seq: l.seq, html: orphanBlock(l, locale) })),
  ].sort((a, b) => a.seq - b.seq);
  const context = locale === "zh" ? scene.context_zh ?? scene.context_en : scene.context_en ?? scene.context_zh;
  const range = clockRange(scene.start_ms, scene.end_ms);
  return `<section class="scene" id="${esc(scene.external_id)}">
  <div class="scene-head"><h3>${esc(fill(L.scene, scene.number))}</h3>${range ? `<span class="small faint">${esc(range)}</span>` : ""}<span class="mono micro faint">${esc(scene.external_id)}</span></div>
  ${context ? `<div class="context"><span class="label">${esc(L.context)}</span><br>${escMultiline(context)}</div>` : ""}
  ${entries.map((e) => e.html).join("\n")}
</section>`;
}

export function diffDocumentHtml(i: DiffDocumentInput): string {
  const L = LABELS[i.locale];
  const s = i.snapshot;
  const status: VersionStatus = i.version?.status ?? "draft";
  const nameZh = i.title.name_zh || s.title.name_zh;
  const nameEn = s.version.display_title_en ?? i.title.name_en ?? s.title.name_en;
  const epName = i.locale === "zh" ? i.episode.name_zh ?? i.episode.name_en : i.episode.name_en ?? i.episode.name_zh;
  const heading = i.locale === "zh" ? nameZh : nameEn ?? nameZh;
  const subheading = i.locale === "zh" ? nameEn : nameZh;

  const allLines = s.scenes.flatMap((sc) => sc.lines);
  const allAdapted = s.scenes.flatMap((sc) => sc.adapted_lines);
  const changed = allAdapted.filter((a) => a.change_type !== "keep" && a.change_type !== "literal").length;
  const majors = s.scenes.flatMap((sc) =>
    joinScene(sc).joined.filter((j) => j.adapted.is_major).map((j) => ({ j, scene: sc.number })),
  );

  const approvalLine =
    status === "approved"
      ? i.version?.approval_mode === "on_behalf"
        ? L.approvedOnBehalf
        : L.approved
      : null;

  const meta = metaList([
    [L.versionId, s.version.external_id],
    [L.sha, i.version?.snapshot_sha256 ?? null],
    [L.submitted, fmtDate(i.version?.submitted_at, i.locale)],
    [approvalLine ?? L.approved, status === "approved" ? fmtDate(i.version?.approved_at, i.locale) || "—" : null],
    [L.producer, i.producer_name ?? null],
    [L.target, s.version.target_locale],
    [L.scenes, String(s.scenes.length)],
    [L.lines, String(allLines.length)],
    [L.changed, String(changed)],
  ]);

  const body = `<header class="head">
  <div>
    <div class="label">${esc(L.doc)}</div>
    <h1>${esc(heading)}</h1>
    ${subheading ? `<div class="sub muted">${esc(subheading)}</div>` : ""}
    <div class="sub">${esc(fill(L.episode, i.episode.number))}${epName ? ` · ${esc(epName)}` : ""} · ${esc(L.version)} ${s.version.number}</div>
  </div>
  <div>${pill(L.status[status], statusTone(status))}</div>
</header>
${meta}

<h2>${esc(L.major)}</h2>
<p class="small muted">${esc(L.majorIntro)}</p>
${majors.length ? majors.map(({ j, scene }) => lineBlock(j, i.locale, scene)).join("\n") : `<p class="small faint" style="margin-top:8px">${esc(L.majorNone)}</p>`}

${s.scenes.map((sc) => sceneSection(sc, i.locale)).join("\n")}

<footer class="foot">${esc(L.foot)}</footer>`;

  return docShell({
    lang: i.locale,
    title: `${heading} · ${fill(L.episode, i.episode.number)} · ${L.doc}`,
    body,
  });
}
