// The title package: everything a platform's content team needs to list the
// show — title options with the platform pick first, short descriptions,
// thumbnail concepts as text, and the ad angles. Dismissed variants stay
// out. English by default (the platform is in the U.S.); the Chinese
// rendering of each variant rides underneath when the model produced one,
// so the producer can read the same page.

import { AD_ANGLE_LABELS, type Title, type Variant, type VariantKind } from "@/lib/types";
import { type DocLocale, docShell, esc, escMultiline, metaList, pill } from "./html";

const LABELS = {
  en: {
    doc: "Title package",
    genre: "Genre",
    logline: "Logline",
    synopsis: "Synopsis",
    titles: "Title options",
    hooks: "Hooks",
    descriptions: "Short descriptions",
    thumbs: "Thumbnail concepts",
    angles: "Ad angles",
    pick: "Platform pick",
    why: "Why",
    empty: "Nothing generated yet for this section.",
    foot: "Generated by Pulsar Studio. External ids only.",
  },
  zh: {
    doc: "标题包",
    genre: "类型",
    logline: "一句话梗概",
    synopsis: "剧情简介",
    titles: "美版标题候选",
    hooks: "钩子",
    descriptions: "短简介",
    thumbs: "缩略图概念",
    angles: "投放角度",
    pick: "平台选定",
    why: "理由",
    empty: "该部分尚未生成内容。",
    foot: "由 Pulsar Studio 生成。仅含外部编号。",
  },
} as const;

export type PackageInput = {
  title: Pick<Title, "name_zh" | "name_en" | "external_id" | "genre" | "logline_en" | "logline_zh" | "synopsis_en" | "synopsis_zh">;
  variants: Variant[];
  locale?: DocLocale;
};

const ORDER: Array<{ kind: VariantKind; label: keyof (typeof LABELS)["en"] }> = [
  { kind: "title", label: "titles" },
  { kind: "description", label: "descriptions" },
  { kind: "thumbnail_concept", label: "thumbs" },
  { kind: "hook", label: "hooks" },
  { kind: "ad_angle", label: "angles" },
];

function angleLabel(a: Variant["tags"][number], locale: DocLocale): string {
  const l = AD_ANGLE_LABELS[a];
  return l ? (locale === "zh" ? l.zh : l.en) : a;
}

function card(v: Variant, locale: DocLocale, ordinal: number): string {
  const L = LABELS[locale];
  const why = locale === "zh" ? v.rationale_zh ?? v.rationale_en : v.rationale_en ?? v.rationale_zh;
  return `<div class="card${v.selected ? " pick" : ""}" id="${esc(v.external_id)}">
  <div class="scene-head"><span class="faint small">${ordinal}</span><p style="font-size:15px">${escMultiline(v.text_en)}</p>${v.selected ? pill(L.pick, "accent") : ""}</div>
  ${v.text_zh ? `<p class="small muted" style="margin-top:4px">${escMultiline(v.text_zh)}</p>` : ""}
  ${why ? `<p class="small" style="margin-top:6px"><span class="faint">${esc(L.why)}</span> ${esc(why)}</p>` : ""}
  <div class="tags" style="margin-top:6px">${v.tags.map((t) => pill(angleLabel(t, locale), "neutral")).join("")}<span class="mono micro faint" style="margin-left:6px">${esc(v.external_id)}</span></div>
</div>`;
}

export function packageHtml(i: PackageInput): string {
  const locale: DocLocale = i.locale ?? "en";
  const L = LABELS[locale];
  const heading = locale === "zh" ? i.title.name_zh : i.title.name_en ?? i.title.name_zh;
  const sub = locale === "zh" ? i.title.name_en : i.title.name_zh;
  const logline = locale === "zh" ? i.title.logline_zh ?? i.title.logline_en : i.title.logline_en ?? i.title.logline_zh;
  const synopsis = locale === "zh" ? i.title.synopsis_zh ?? i.title.synopsis_en : i.title.synopsis_en ?? i.title.synopsis_zh;

  const live = i.variants.filter((v) => v.status !== "dismissed");
  const sections = ORDER.map(({ kind, label }) => {
    // The pick leads its section; the rest keep creation order.
    const items = live.filter((v) => v.kind === kind).sort((a, b) => Number(b.selected) - Number(a.selected));
    const bodyHtml = items.length
      ? items.map((v, n) => card(v, locale, n + 1)).join("\n")
      : `<p class="small faint" style="margin-top:8px">${esc(L.empty)}</p>`;
    return `<h2>${esc(L[label])}</h2>\n${bodyHtml}`;
  }).join("\n\n");

  const body = `<header class="head">
  <div>
    <div class="label">${esc(L.doc)}</div>
    <h1>${esc(heading)}</h1>
    ${sub ? `<div class="sub muted">${esc(sub)}</div>` : ""}
  </div>
  <div class="mono micro faint">${esc(i.title.external_id)}</div>
</header>
${metaList([
  [L.genre, i.title.genre],
  [L.logline, logline],
])}
${synopsis ? `<h2>${esc(L.synopsis)}</h2><p class="small" style="margin-top:8px">${escMultiline(synopsis)}</p>` : ""}

${sections}

<footer class="foot">${esc(L.foot)}</footer>`;

  return docShell({ lang: locale, title: `${heading} · ${L.doc}`, body });
}
